package com.wayto.android.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig workRecordTableDaoConfig;
    private final DaoConfig uploadingTableDaoConfig;

    private final WorkRecordTableDao workRecordTableDao;
    private final UploadingTableDao uploadingTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        workRecordTableDaoConfig = daoConfigMap.get(WorkRecordTableDao.class).clone();
        workRecordTableDaoConfig.initIdentityScope(type);

        uploadingTableDaoConfig = daoConfigMap.get(UploadingTableDao.class).clone();
        uploadingTableDaoConfig.initIdentityScope(type);

        workRecordTableDao = new WorkRecordTableDao(workRecordTableDaoConfig, this);
        uploadingTableDao = new UploadingTableDao(uploadingTableDaoConfig, this);

        registerDao(WorkRecordTable.class, workRecordTableDao);
        registerDao(UploadingTable.class, uploadingTableDao);
    }
    
    public void clear() {
        workRecordTableDaoConfig.clearIdentityScope();
        uploadingTableDaoConfig.clearIdentityScope();
    }

    public WorkRecordTableDao getWorkRecordTableDao() {
        return workRecordTableDao;
    }

    public UploadingTableDao getUploadingTableDao() {
        return uploadingTableDao;
    }

}
